const { createClient } = require("@supabase/supabase-js");

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseKey =
  process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_ANON_KEY;

let client = null;

function getClient() {
  if (!supabaseUrl || !supabaseKey) {
    throw new Error(
      "Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY/SUPABASE_ANON_KEY"
    );
  }
  if (!client) {
    client = createClient(supabaseUrl, supabaseKey);
  }
  return client;
}

const ORDERS_TABLE = "orders";

/**
 * Insert a new order. Row: items (jsonb), total, status, created_at. id is generated by DB.
 * @returns {Promise<{ data: { orderId, total, status } | null, error }>}
 */
async function createOrder({ items, total, status, createdAt }) {
  const supabase = getClient();
  const { data, error } = await supabase
    .from(ORDERS_TABLE)
    .insert({
      items,
      total: Number(total),
      status: status || "new",
      created_at: createdAt || new Date().toISOString(),
    })
    .select("id, total, status")
    .single();

  if (error) return { data: null, error };
  return {
    data: {
      orderId: data.id,
      total: data.total,
      status: data.status,
    },
    error: null,
  };
}

/**
 * Get order by id (uuid).
 * @returns {Promise<{ data: object | null, error: object | null }>}
 */
async function getOrderById(orderId) {
  const supabase = getClient();
  const { data, error } = await supabase
    .from(ORDERS_TABLE)
    .select("id, items, total, status, created_at")
    .eq("id", orderId)
    .maybeSingle();

  if (error) return { data: null, error };
  if (!data) return { data: null, error: null };
  return {
    data: {
      orderId: data.id,
      items: data.items,
      total: data.total,
      status: data.status,
      createdAt: data.created_at,
    },
    error: null,
  };
}

module.exports = {
  getClient,
  createOrder,
  getOrderById,
  ORDERS_TABLE,
};
